# Generated by Django 5.0.6 on 2024-05-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
