# Generated by Django 5.0.6 on 2024-05-12 07:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_name', models.CharField(max_length=10000)),
                ('relation_gps', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
