# Generated by Django 5.0.6 on 2024-05-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
