# Generated by Django 5.0.6 on 2024-05-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_gps',
        ),
    ]
