# Generated by Django 5.0.6 on 2024-05-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='station',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='relation',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
