# Generated by Django 5.0.6 on 2024-05-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0014_relation_delete_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
