# Generated by Django 5.0.6 on 2024-05-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0017_route_delete_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
