# Generated by Django 5.0.6 on 2024-05-21 04:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0020_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=500)),
                ('route_gps', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('station', models.ManyToManyField(related_name='route', to='predictor.station')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timetable_relation', to='predictor.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timetable_station', to='predictor.station')),
            ],
        ),
    ]
