# Generated by Django 5.0.6 on 2024-05-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0021_route_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='route',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='station',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
