# Generated by Django 5.0.6 on 2024-05-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0027_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
