# Generated by Django 5.0.6 on 2024-05-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0030_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
