# Generated by Django 5.0.6 on 2024-05-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0034_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='route',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='station',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
