# Generated by Django 5.0.6 on 2024-05-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0037_alter_route_route_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='route',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='station',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='stations',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
