# Generated by Django 5.0.6 on 2024-05-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0043_schedule_timetable_schedule_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='route',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='station',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='stations',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
