# Generated by Django 5.0.6 on 2024-06-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0054_railwaydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RailwayData',
        ),
    ]
